AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Production environment: Transit Gateway.  
Parameters:
  TagProject:
    Type: String
    Description: 'Tag: project'
    Default: tgw-us-west-2
  TagAdmin:
    Type: String
    Description: 'Tag: project admin (uid)'
    Default: jkhong
  TagEnvironment:
    Type: String
    Description: 'Tag: project environment enter - Development, Test, Staging, Production'
    Default: Production
  TagOwner:
    Type: String
    Description: 'Tag: project owner (uid)'
    Default: corley


  BucketWWWLogsCloudtrail:
    Type: String
    Description: cloudtrail log bucket to create
    Default: tgw-us-west-2-hub-cloudtrail


Resources:
  S3BucketWWWLogsCloudtrail:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketWWWLogsCloudtrail
      Tags:
        - Key: Project
          Value: !Ref TagProject
        - Key: Admin
          Value: !Ref TagAdmin
        - Key: AppEnv
          Value: !Ref TagEnvironment
        - Key: Owner
          Value: !Ref TagOwner
      LifecycleConfiguration:
        Rules:
          - Id: Expire365days
            ExpirationInDays: '365'
            Prefix: ''
            Status: Enabled
    DeletionPolicy: Retain
  S3BucketWWWLogsCloudtrailBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref BucketWWWLogsCloudtrail
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref BucketWWWLogsCloudtrail
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref BucketWWWLogsCloudtrail
                - /AWSLogs/
                - !Ref 'AWS::AccountId'
                - /*
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
    DependsOn: S3BucketWWWLogsCloudtrail
  TopicCloudTrail:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: cloudtrail-allregions
  TopicPolicyCloudTrail:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics:
        - !Ref TopicCloudTrail
      PolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: AWSCloudTrailSNSPolicy
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Resource: '*'
            Action: 'SNS:Publish'
  TrailWWW:
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      S3BucketName: !Ref S3BucketWWWLogsCloudtrail
      SnsTopicName: !GetAtt 
        - TopicCloudTrail
        - TopicName
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      TrailName: uschomepage-allregions
    DependsOn:
      - S3BucketWWWLogsCloudtrailBucketPolicy
      - TopicPolicyCloudTrail


Outputs:
  S3Cloudtrail:
    Value: !Ref S3BucketWWWLogsCloudtrail
    Description: The S3 Cloudtrail bucket

