AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for to create a transit gateway and customer gateway
Parameters:
  TagAdmin:
    Type: String
    Default: jkhong
    Description: 'Tag: project admin (uid)'
  TagEnvironment:
    Type: String
    Default: Production
    Description: 'Tag: project environment enter - Development, Test, Staging, Production'
  TagOwner:
    Type: String
    Default: dcorley
    Description: 'Tag: project owner (uid)'
  TagProject:
    Type: String
    Default: its-tgw-us-west-2
    Description: 'Tag: project'

Resources:
  HubTransitGatewayAuto:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: 65001
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
#      Description: String
      DnsSupport: enable
      VpnEcmpSupport: enable
      Tags: 
        - Key: Name
          Value: !Join ['-', [!Ref 'AWS::StackName', 'tgw-auto']]
        - Key: Admin
          Value: !Ref 'TagAdmin'
        - Key: AppEnv
          Value: !Ref 'TagEnvironment'
        - Key: Owner
          Value: !Ref 'TagOwner'
        - Key: Project
          Value: !Ref 'TagProject'
          
  HubCustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties:
      BgpAsn: 64512
      IpAddress: 128.125.255.190
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref 'AWS::StackName', 'cgw-fwc01']]
        - Key: Admin
          Value: !Ref 'TagAdmin'
        - Key: AppEnv
          Value: !Ref 'TagEnvironment'
        - Key: Owner
          Value: !Ref 'TagOwner'
        - Key: Project
          Value: !Ref 'TagProject'
      Type: ipsec.1
  HubCustomerGateway2:
    Type: AWS::EC2::CustomerGateway
    Properties:
      BgpAsn: 64901
      IpAddress: 207.151.53.254 
      Tags:
        - Key: Name
          Value: cgw-207-151-53-254-asn64901
        - Key: Admin
          Value: !Ref 'TagAdmin'
        - Key: AppEnv
          Value: !Ref 'TagEnvironment'
        - Key: Owner
          Value: !Ref 'TagOwner'
        - Key: Project
          Value: !Ref 'TagProject'
      Type: ipsec.1
#  HubVPNConnection:
#    Type: AWS::EC2::VPNConnection
#    Properties:
#      Type: ipsec.1
#      CustomerGatewayId: !Ref 'HubCustomerGateway'
#      StaticRoutesOnly: false
#      Tags: 
#        - Key: Name
#          Value: !Join ['-', [!Ref 'AWS::StackName', 'vpn-fwc01']]
#      VpnGatewayId: !Ref 'HubVPNGateway'
#      VpnTunnelOptionsSpecifications: String


